services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: mariadb:10.10.7
    restart: always
    secrets:
      - db-secret
    volumes:
      # Volume de la base de données
      - ./db-data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-secret
    ports:
      - "3306:3306"

web:
    build:
      context: .
      target: web/Dockerfile
    restart: always
    secrets:
      - db-secret
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:

secrets:
  db-secret:
    file: db/secret.txt
   
    networks:
      backend:
